version: '3.8'

services:
  web:
    build:
      context: ../
    restart: always
    volumes:
      - static_value:/app/static/
      - static_value:/app/media/
    env_file:
      - ../.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - web

volumes:
  static_value:
  media_value: